# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdcfda379143569595c7496be8f12788b1cdc4c9b39f0a9f88d3571732a8ff1c1fc151917d7d435181e342ad72d809eb546e5bc55d920d4a201b820712c42f12

test:
  secret_key_base: a97595396df76c96e508fcb4fdf4cbb6d4c3f3237ebe9d0bcf19f9d5723afeda938bd0aa240357dcfdf022e7ff5c394efa8ccd202f218fd8bf41cb8b40f6fa8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
